[project]
name = "ezMM"
version = "0.6.0"
description = "Lightweight Python kit for easy multimodal data processing."
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
authors = [{name = "Mark Rothermel", email = "mark.rothermel@tu-darmstadt.de"}]
dependencies = [
    "pillow~=12.3.0",
    "pillow-avif-plugin==1.6.0",
    "opencv-python~=5.0.0.93",
    "markdown~=3.10.2",
    "imageio-ffmpeg",
    "m3u8",
    "jinja2",
    "fastembed",
    "mutagen",
]

[project.optional-dependencies]
ui = [
    "uvicorn~=0.51.0",
    "fastapi~=0.139.2",
    "starlette~=1.3.1",
]
test = [
    "pytest",
    "pytest-asyncio",
    "httpx",
    # For visual display
    "uvicorn~=0.51.0",
    "fastapi~=0.139.2",
    "starlette~=1.3.1",
]

[project.scripts]
ezmm = "ezmm.__main__:main"

[project.urls]
"Homepage" = "https://github.com/multimodal-ai-lab/ezmm"
"Issues" = "https://github.com/multimodal-ai-lab/ezmm/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools.package-data]
ezmm = ["ui/templates/*", "ui/static/*"]
